# Generated by Django 5.2.1 on 2025-08-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
